# Form implementation generated from reading ui file '.\overlay.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Overlay(object):
    def setupUi(self, Overlay):
        Overlay.setObjectName("Overlay")
        Overlay.resize(1855, 1091)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setBold(True)
        font.setUnderline(False)
        Overlay.setFont(font)
        self.listView = QtWidgets.QListView(parent=Overlay)
        self.listView.setGeometry(QtCore.QRect(1350, 160, 521, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listView.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.listView.setFont(font)
        self.listView.setStyleSheet("QListView {\n"
"    background-color: rgba(40, 42, 54, 0.95); \n"
"    border: 2px solid #4A4D5E;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    color: #E3E6EE;\n"
"    font: 11pt \"Inter\";\n"
"    backdrop-filter: blur(10px); \n"
"}\n"
"\n"
"")
        self.listView.setObjectName("listView")
        self.ObjectTypeLabel = QtWidgets.QLabel(parent=Overlay)
        self.ObjectTypeLabel.setGeometry(QtCore.QRect(1530, 250, 191, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ObjectTypeLabel.sizePolicy().hasHeightForWidth())
        self.ObjectTypeLabel.setSizePolicy(sizePolicy)
        self.ObjectTypeLabel.setBaseSize(QtCore.QSize(-30172, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.ObjectTypeLabel.setFont(font)
        self.ObjectTypeLabel.setToolTipDuration(-1)
        self.ObjectTypeLabel.setStyleSheet("QLabel { color: white; font-size: 40px; font-family: Bahnschrift; }")
        self.ObjectTypeLabel.setText("Planet")
        self.ObjectTypeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ObjectTypeLabel.setObjectName("ObjectTypeLabel")
        self.ObjectAttributeLabel = QtWidgets.QLabel(parent=Overlay)
        self.ObjectAttributeLabel.setGeometry(QtCore.QRect(1370, 450, 491, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ObjectAttributeLabel.sizePolicy().hasHeightForWidth())
        self.ObjectAttributeLabel.setSizePolicy(sizePolicy)
        self.ObjectAttributeLabel.setBaseSize(QtCore.QSize(-30172, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.ObjectAttributeLabel.setFont(font)
        self.ObjectAttributeLabel.setToolTipDuration(-1)
        self.ObjectAttributeLabel.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.ObjectAttributeLabel.setText("<html><head/><body><p>Mass: 6.3e13 kg</p><p>Orbitradius: 2.42e3 km</p><p>Radius: 6371km</p><p>Surface Gravity: 9.81 m/s</p><p>Day (Rotation): 24h</p><p>Year (Revolution): 365d</p><p>nat. Satellites: 1 (Moon)</p><p><br/></p><p><br/></p></body></html>")
        self.ObjectAttributeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ObjectAttributeLabel.setObjectName("ObjectAttributeLabel")
        self.ObjectNameLabel = QtWidgets.QLabel(parent=Overlay)
        self.ObjectNameLabel.setGeometry(QtCore.QRect(1530, 320, 191, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ObjectNameLabel.sizePolicy().hasHeightForWidth())
        self.ObjectNameLabel.setSizePolicy(sizePolicy)
        self.ObjectNameLabel.setBaseSize(QtCore.QSize(-30172, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.ObjectNameLabel.setFont(font)
        self.ObjectNameLabel.setToolTipDuration(-1)
        self.ObjectNameLabel.setStyleSheet("QLabel { color: white; font-size: 35px; font-family: Bahnschrift; }")
        self.ObjectNameLabel.setText("Earth")
        self.ObjectNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ObjectNameLabel.setObjectName("ObjectNameLabel")
        self.timeSlider = QtWidgets.QSlider(parent=Overlay)
        self.timeSlider.setGeometry(QtCore.QRect(120, 20, 160, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeSlider.sizePolicy().hasHeightForWidth())
        self.timeSlider.setSizePolicy(sizePolicy)
        self.timeSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background: #2E2F38; \n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #2A2D37;\n"
"    border: 2px solid #3D4250;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: -6px 0;\n"
"    border-radius: 8px;\n"
"    transition: background 0.2s ease-in-out, transform 0.1s ease-in-out;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background:#5A5F74;  \n"
"    transform: scale(1.1); \n"
"}\n"
"\n"
"QSlider::sub-page:horizontal,\n"
"QSlider::add-page:horizontal {\n"
"    background: #2E2F38; \n"
"    border-radius: 3px;\n"
"}")
        self.timeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.sunButton = QtWidgets.QPushButton(parent=Overlay)
        self.sunButton.setGeometry(QtCore.QRect(70, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sunButton.sizePolicy().hasHeightForWidth())
        self.sunButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.sunButton.setFont(font)
        self.sunButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.sunButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.sunButton.setObjectName("sunButton")
        self.neptuneButton = QtWidgets.QPushButton(parent=Overlay)
        self.neptuneButton.setGeometry(QtCore.QRect(1728, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neptuneButton.sizePolicy().hasHeightForWidth())
        self.neptuneButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.neptuneButton.setFont(font)
        self.neptuneButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.neptuneButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.neptuneButton.setObjectName("neptuneButton")
        self.mercuryButton = QtWidgets.QPushButton(parent=Overlay)
        self.mercuryButton.setGeometry(QtCore.QRect(277, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mercuryButton.sizePolicy().hasHeightForWidth())
        self.mercuryButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.mercuryButton.setFont(font)
        self.mercuryButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.mercuryButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.mercuryButton.setObjectName("mercuryButton")
        self.venusButton = QtWidgets.QPushButton(parent=Overlay)
        self.venusButton.setGeometry(QtCore.QRect(484, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.venusButton.sizePolicy().hasHeightForWidth())
        self.venusButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.venusButton.setFont(font)
        self.venusButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.venusButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.venusButton.setObjectName("venusButton")
        self.marsButton = QtWidgets.QPushButton(parent=Overlay)
        self.marsButton.setGeometry(QtCore.QRect(898, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.marsButton.sizePolicy().hasHeightForWidth())
        self.marsButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.marsButton.setFont(font)
        self.marsButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.marsButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.marsButton.setObjectName("marsButton")
        self.earthButton = QtWidgets.QPushButton(parent=Overlay)
        self.earthButton.setGeometry(QtCore.QRect(691, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.earthButton.sizePolicy().hasHeightForWidth())
        self.earthButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.earthButton.setFont(font)
        self.earthButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.earthButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.earthButton.setObjectName("earthButton")
        self.jupiterButton = QtWidgets.QPushButton(parent=Overlay)
        self.jupiterButton.setGeometry(QtCore.QRect(1105, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jupiterButton.sizePolicy().hasHeightForWidth())
        self.jupiterButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.jupiterButton.setFont(font)
        self.jupiterButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.jupiterButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.jupiterButton.setObjectName("jupiterButton")
        self.uranusButton = QtWidgets.QPushButton(parent=Overlay)
        self.uranusButton.setGeometry(QtCore.QRect(1520, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uranusButton.sizePolicy().hasHeightForWidth())
        self.uranusButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.uranusButton.setFont(font)
        self.uranusButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.uranusButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.uranusButton.setObjectName("uranusButton")
        self.saturnButton = QtWidgets.QPushButton(parent=Overlay)
        self.saturnButton.setGeometry(QtCore.QRect(1313, 1010, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saturnButton.sizePolicy().hasHeightForWidth())
        self.saturnButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.saturnButton.setFont(font)
        self.saturnButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.saturnButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37;\n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.saturnButton.setObjectName("saturnButton")
        self.fps_text = QtWidgets.QLabel(parent=Overlay)
        self.fps_text.setGeometry(QtCore.QRect(40, 20, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fps_text.sizePolicy().hasHeightForWidth())
        self.fps_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.fps_text.setFont(font)
        self.fps_text.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.fps_text.setObjectName("fps_text")
        self.simulation_speed_text = QtWidgets.QLabel(parent=Overlay)
        self.simulation_speed_text.setGeometry(QtCore.QRect(170, 50, 81, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulation_speed_text.sizePolicy().hasHeightForWidth())
        self.simulation_speed_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        self.simulation_speed_text.setFont(font)
        self.simulation_speed_text.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.simulation_speed_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.simulation_speed_text.setObjectName("simulation_speed_text")
        self.PerformanceModeCheckbox = QtWidgets.QCheckBox(parent=Overlay)
        self.PerformanceModeCheckbox.setGeometry(QtCore.QRect(30, 210, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PerformanceModeCheckbox.sizePolicy().hasHeightForWidth())
        self.PerformanceModeCheckbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.PerformanceModeCheckbox.setFont(font)
        self.PerformanceModeCheckbox.setStyleSheet("QCheckBox {\n"
"    spacing: 10px;       \n"
"    font-size: 16px;\n"
"    color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"\n"
"    border: 2px solid #fff;\n"
"    border-radius: 4px;  \n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #fff;\n"
"    border: 2px solid #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    border: 2px solid #ccc;\n"
"    background: #f0f0f0;\n"
"}\n"
"")
        self.PerformanceModeCheckbox.setObjectName("PerformanceModeCheckbox")
        self.TimeCounter = QtWidgets.QLabel(parent=Overlay)
        self.TimeCounter.setGeometry(QtCore.QRect(1600, 20, 371, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeCounter.sizePolicy().hasHeightForWidth())
        self.TimeCounter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.TimeCounter.setFont(font)
        self.TimeCounter.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.TimeCounter.setObjectName("TimeCounter")
        self.Create_Button = QtWidgets.QPushButton(parent=Overlay)
        self.Create_Button.setGeometry(QtCore.QRect(20, 340, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Create_Button.sizePolicy().hasHeightForWidth())
        self.Create_Button.setSizePolicy(sizePolicy)
        self.Create_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; \n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250;\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; \n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028;\n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.Create_Button.setObjectName("Create_Button")
        self.listView_2 = QtWidgets.QListView(parent=Overlay)
        self.listView_2.setGeometry(QtCore.QRect(20, 440, 421, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_2.sizePolicy().hasHeightForWidth())
        self.listView_2.setSizePolicy(sizePolicy)
        self.listView_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listView_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.listView_2.setFont(font)
        self.listView_2.setStyleSheet("QListView {\n"
"    background-color: rgba(40, 42, 54, 0.95);\n"
"    border: 2px solid #4A4D5E;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    color: #E3E6EE;\n"
"    font: 11pt \"Inter\";\n"
"    backdrop-filter: blur(10px);\n"
"}\n"
"\n"
"QListView::item {\n"
"    background-color: transparent;\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid rgba(100, 110, 130, 0.2)\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    background-color: #3D4250; \n"
"    color: white;\n"
"    border: 1px solid #6A6F85;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #4A5062;\n"
"    color: white;\n"
"}")
        self.listView_2.setObjectName("listView_2")
        self.NameText = QtWidgets.QLabel(parent=Overlay)
        self.NameText.setGeometry(QtCore.QRect(40, 460, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameText.sizePolicy().hasHeightForWidth())
        self.NameText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.NameText.setFont(font)
        self.NameText.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.NameText.setObjectName("NameText")
        self.lineEditName = QtWidgets.QLineEdit(parent=Overlay)
        self.lineEditName.setGeometry(QtCore.QRect(120, 460, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditName.sizePolicy().hasHeightForWidth())
        self.lineEditName.setSizePolicy(sizePolicy)
        self.lineEditName.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: #2A2D37;   \n"
"    color: #E3E6EE;             \n"
"    font: bold 12pt \"Bahnschrift\";  \n"
"    border: 2px solid #3D4250;     \n"
"    border-radius: 10px;          \n"
"    padding: 6px 12px;              \n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: inset 0px 2px 4px rgba(0,0,0,0.4);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #343844;     \n"
"    border-color: #4A4F63;        \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;     \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #1E2028;     \n"
"    color: #777A87;              \n"
"    border-color: #2C2F38;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"0\"]::placeholder {\n"
"    color: #A0A3B1;              \n"
"    font: italic 12pt \"Bahnschrift\";\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.lineEditName.setObjectName("lineEditName")
        self.MassText = QtWidgets.QLabel(parent=Overlay)
        self.MassText.setGeometry(QtCore.QRect(40, 520, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MassText.sizePolicy().hasHeightForWidth())
        self.MassText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.MassText.setFont(font)
        self.MassText.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.MassText.setObjectName("MassText")
        self.SizeText = QtWidgets.QLabel(parent=Overlay)
        self.SizeText.setGeometry(QtCore.QRect(40, 580, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeText.sizePolicy().hasHeightForWidth())
        self.SizeText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.SizeText.setFont(font)
        self.SizeText.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.SizeText.setObjectName("SizeText")
        self.CreateAftertInputButton = QtWidgets.QPushButton(parent=Overlay)
        self.CreateAftertInputButton.setGeometry(QtCore.QRect(160, 710, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateAftertInputButton.sizePolicy().hasHeightForWidth())
        self.CreateAftertInputButton.setSizePolicy(sizePolicy)
        self.CreateAftertInputButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; \n"
"    color: #E3E6EE; \n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250;\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; \n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.CreateAftertInputButton.setObjectName("CreateAftertInputButton")
        self.VelocityText = QtWidgets.QLabel(parent=Overlay)
        self.VelocityText.setGeometry(QtCore.QRect(40, 640, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VelocityText.sizePolicy().hasHeightForWidth())
        self.VelocityText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.VelocityText.setFont(font)
        self.VelocityText.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.VelocityText.setObjectName("VelocityText")
        self.CreationModeCheckbox = QtWidgets.QCheckBox(parent=Overlay)
        self.CreationModeCheckbox.setGeometry(QtCore.QRect(30, 270, 281, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreationModeCheckbox.sizePolicy().hasHeightForWidth())
        self.CreationModeCheckbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.CreationModeCheckbox.setFont(font)
        self.CreationModeCheckbox.setStyleSheet("QCheckBox {\n"
"    spacing: 10px;       \n"
"    font-size: 16px;\n"
"    color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"\n"
"    border: 2px solid #fff;\n"
"    border-radius: 4px;  \n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #fff;\n"
"    border: 2px solid #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    border: 2px solid #ccc;\n"
"    background: #f0f0f0;\n"
"}\n"
"")
        self.CreationModeCheckbox.setObjectName("CreationModeCheckbox")
        self.lineEditMass = QtWidgets.QLineEdit(parent=Overlay)
        self.lineEditMass.setGeometry(QtCore.QRect(120, 520, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMass.sizePolicy().hasHeightForWidth())
        self.lineEditMass.setSizePolicy(sizePolicy)
        self.lineEditMass.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: #2A2D37;   \n"
"    color: #E3E6EE;             \n"
"    font: bold 12pt \"Bahnschrift\";  \n"
"    border: 2px solid #3D4250;     \n"
"    border-radius: 10px;          \n"
"    padding: 6px 12px;              \n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: inset 0px 2px 4px rgba(0,0,0,0.4);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #343844;     \n"
"    border-color: #4A4F63;        \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;     \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #1E2028;     \n"
"    color: #777A87;              \n"
"    border-color: #2C2F38;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"0\"]::placeholder {\n"
"    color: #A0A3B1;              \n"
"    font: italic 12pt \"Bahnschrift\";\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.lineEditMass.setObjectName("lineEditMass")
        self.lineEditSize = QtWidgets.QLineEdit(parent=Overlay)
        self.lineEditSize.setGeometry(QtCore.QRect(120, 580, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSize.sizePolicy().hasHeightForWidth())
        self.lineEditSize.setSizePolicy(sizePolicy)
        self.lineEditSize.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: #2A2D37;   \n"
"    color: #E3E6EE;             \n"
"    font: bold 12pt \"Bahnschrift\";  \n"
"    border: 2px solid #3D4250;     \n"
"    border-radius: 10px;          \n"
"    padding: 6px 12px;              \n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: inset 0px 2px 4px rgba(0,0,0,0.4);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #343844;     \n"
"    border-color: #4A4F63;        \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;     \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #1E2028;     \n"
"    color: #777A87;              \n"
"    border-color: #2C2F38;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"0\"]::placeholder {\n"
"    color: #A0A3B1;              \n"
"    font: italic 12pt \"Bahnschrift\";\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.lineEditSize.setObjectName("lineEditSize")
        self.lineEditSpeed = QtWidgets.QLineEdit(parent=Overlay)
        self.lineEditSpeed.setGeometry(QtCore.QRect(120, 640, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSpeed.sizePolicy().hasHeightForWidth())
        self.lineEditSpeed.setSizePolicy(sizePolicy)
        self.lineEditSpeed.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: #2A2D37;   \n"
"    color: #E3E6EE;             \n"
"    font: bold 12pt \"Bahnschrift\";  \n"
"    border: 2px solid #3D4250;     \n"
"    border-radius: 10px;          \n"
"    padding: 6px 12px;              \n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: inset 0px 2px 4px rgba(0,0,0,0.4);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #343844;     \n"
"    border-color: #4A4F63;        \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;     \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #1E2028;     \n"
"    color: #777A87;              \n"
"    border-color: #2C2F38;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"0\"]::placeholder {\n"
"    color: #A0A3B1;              \n"
"    font: italic 12pt \"Bahnschrift\";\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.lineEditSpeed.setObjectName("lineEditSpeed")
        self.RerunButton = QtWidgets.QPushButton(parent=Overlay)
        self.RerunButton.setGeometry(QtCore.QRect(30, 80, 91, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RerunButton.sizePolicy().hasHeightForWidth())
        self.RerunButton.setSizePolicy(sizePolicy)
        self.RerunButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; \n"
"    color: #E3E6EE;\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; \n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844;\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028;\n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.RerunButton.setObjectName("RerunButton")
        self.WarningText = QtWidgets.QLabel(parent=Overlay)
        self.WarningText.setGeometry(QtCore.QRect(20, 780, 421, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WarningText.sizePolicy().hasHeightForWidth())
        self.WarningText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.WarningText.setFont(font)
        self.WarningText.setStyleSheet("QLabel { color: yellow; font-size: 20px; font-family: Bahnschrift; }")
        self.WarningText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.WarningText.setObjectName("WarningText")
        self.Scale = QtWidgets.QLabel(parent=Overlay)
        self.Scale.setGeometry(QtCore.QRect(210, 100, 241, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale.sizePolicy().hasHeightForWidth())
        self.Scale.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        self.Scale.setFont(font)
        self.Scale.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.Scale.setText("")
        self.Scale.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Scale.setObjectName("Scale")
        self.showMoonsCheckbox = QtWidgets.QCheckBox(parent=Overlay)
        self.showMoonsCheckbox.setGeometry(QtCore.QRect(30, 150, 281, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showMoonsCheckbox.sizePolicy().hasHeightForWidth())
        self.showMoonsCheckbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.showMoonsCheckbox.setFont(font)
        self.showMoonsCheckbox.setStyleSheet("QCheckBox {\n"
"    spacing: 10px;       \n"
"    font-size: 16px;\n"
"    color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"\n"
"    border: 2px solid #fff;\n"
"    border-radius: 4px;  \n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #fff;\n"
"    border: 2px solid #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    border: 2px solid #ccc;\n"
"    background: #f0f0f0;\n"
"}\n"
"")
        self.showMoonsCheckbox.setObjectName("showMoonsCheckbox")
        self.InfoHints = QtWidgets.QLabel(parent=Overlay)
        self.InfoHints.setGeometry(QtCore.QRect(726, 20, 401, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoHints.sizePolicy().hasHeightForWidth())
        self.InfoHints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.InfoHints.setFont(font)
        self.InfoHints.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.InfoHints.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.InfoHints.setText("")
        self.InfoHints.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.InfoHints.setObjectName("InfoHints")
        self.InfoHints_2 = QtWidgets.QLabel(parent=Overlay)
        self.InfoHints_2.setGeometry(QtCore.QRect(626, 20, 591, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoHints_2.sizePolicy().hasHeightForWidth())
        self.InfoHints_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.InfoHints_2.setFont(font)
        self.InfoHints_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.InfoHints_2.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.InfoHints_2.setText("")
        self.InfoHints_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.InfoHints_2.setObjectName("InfoHints_2")

        self.retranslateUi(Overlay)
        QtCore.QMetaObject.connectSlotsByName(Overlay)

    def retranslateUi(self, Overlay):
        _translate = QtCore.QCoreApplication.translate
        Overlay.setWindowTitle(_translate("Overlay", "Form"))
        self.sunButton.setText(_translate("Overlay", "SUN"))
        self.neptuneButton.setText(_translate("Overlay", "NEPTUNE"))
        self.mercuryButton.setText(_translate("Overlay", "MERCURY"))
        self.venusButton.setText(_translate("Overlay", "VENUS"))
        self.marsButton.setText(_translate("Overlay", "MARS"))
        self.earthButton.setText(_translate("Overlay", "EARTH"))
        self.jupiterButton.setText(_translate("Overlay", "JUPITER"))
        self.uranusButton.setText(_translate("Overlay", "URANUS"))
        self.saturnButton.setText(_translate("Overlay", "SATURN"))
        self.fps_text.setText(_translate("Overlay", "FPS: 60"))
        self.simulation_speed_text.setText(_translate("Overlay", "1"))
        self.PerformanceModeCheckbox.setText(_translate("Overlay", "Performance Mode"))
        self.TimeCounter.setText(_translate("Overlay", "Time Passed: 1 Year 2h 11 Min."))
        self.Create_Button.setText(_translate("Overlay", "Create Object"))
        self.NameText.setText(_translate("Overlay", "Name: "))
        self.lineEditName.setPlaceholderText(_translate("Overlay", "MyObject"))
        self.MassText.setText(_translate("Overlay", "Mass: "))
        self.SizeText.setText(_translate("Overlay", "Size:"))
        self.CreateAftertInputButton.setText(_translate("Overlay", "Create"))
        self.VelocityText.setText(_translate("Overlay", "Speed : "))
        self.CreationModeCheckbox.setText(_translate("Overlay", "Creation Mode "))
        self.lineEditMass.setPlaceholderText(_translate("Overlay", "1000 (*10e23)"))
        self.lineEditSize.setPlaceholderText(_translate("Overlay", "123  (max. 999)"))
        self.lineEditSpeed.setPlaceholderText(_translate("Overlay", "123456 m/s "))
        self.RerunButton.setText(_translate("Overlay", "Rerun"))
        self.WarningText.setText(_translate("Overlay", "WARNING: Size is low"))
        self.showMoonsCheckbox.setText(_translate("Overlay", " Moons"))
