# Form implementation generated from reading ui file '.\overlay.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Overlay(object):
    def setupUi(self, Overlay):
        Overlay.setObjectName("Overlay")
        Overlay.resize(1920, 1091)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setBold(True)
        font.setUnderline(False)
        Overlay.setFont(font)
        self.listView = QtWidgets.QListView(parent=Overlay)
        self.listView.setGeometry(QtCore.QRect(1260, 160, 521, 681))
        self.listView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listView.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.listView.setFont(font)
        self.listView.setStyleSheet("QListView {\n"
"    background-color: rgba(40, 42, 54, 0.95); /* Slight transparency effect */\n"
"    border: 2px solid #4A4D5E;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    color: #E3E6EE;\n"
"    font: 11pt \"Inter\";\n"
"    backdrop-filter: blur(10px); /* Smooth glass effect */\n"
"}\n"
"\n"
"/* List Items */\n"
"QListView::item {\n"
"    background-color: transparent;\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid rgba(100, 110, 130, 0.2); /* Soft dividers */\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    background-color: #3D4250; /* Sleek selection effect */\n"
"    color: white;\n"
"    border: 1px solid #6A6F85;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #4A5062;\n"
"    color: white;\n"
"}")
        self.listView.setObjectName("listView")
        self.ObjectTypeLabel = QtWidgets.QLabel(parent=Overlay)
        self.ObjectTypeLabel.setGeometry(QtCore.QRect(1440, 250, 191, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ObjectTypeLabel.sizePolicy().hasHeightForWidth())
        self.ObjectTypeLabel.setSizePolicy(sizePolicy)
        self.ObjectTypeLabel.setBaseSize(QtCore.QSize(-30172, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.ObjectTypeLabel.setFont(font)
        self.ObjectTypeLabel.setToolTipDuration(-1)
        self.ObjectTypeLabel.setStyleSheet("QLabel { color: white; font-size: 40px; font-family: Bahnschrift; }")
        self.ObjectTypeLabel.setText("Planet")
        self.ObjectTypeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ObjectTypeLabel.setObjectName("ObjectTypeLabel")
        self.ObjectAttributeLabel = QtWidgets.QLabel(parent=Overlay)
        self.ObjectAttributeLabel.setGeometry(QtCore.QRect(1280, 450, 491, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ObjectAttributeLabel.sizePolicy().hasHeightForWidth())
        self.ObjectAttributeLabel.setSizePolicy(sizePolicy)
        self.ObjectAttributeLabel.setBaseSize(QtCore.QSize(-30172, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.ObjectAttributeLabel.setFont(font)
        self.ObjectAttributeLabel.setToolTipDuration(-1)
        self.ObjectAttributeLabel.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.ObjectAttributeLabel.setText("<html><head/><body><p>Mass: 6.3e13 kg</p><p>Orbitradius: 2.42e3 km</p><p>Radius: 6371km</p><p>Surface Gravity: 9.81 m/s</p><p>Day (Rotation): 24h</p><p>Year (Revolution): 365d</p><p>nat. Satellites: 1 (Moon)</p><p><br/></p><p><br/></p></body></html>")
        self.ObjectAttributeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ObjectAttributeLabel.setObjectName("ObjectAttributeLabel")
        self.ObjectNameLabel = QtWidgets.QLabel(parent=Overlay)
        self.ObjectNameLabel.setGeometry(QtCore.QRect(1440, 320, 191, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ObjectNameLabel.sizePolicy().hasHeightForWidth())
        self.ObjectNameLabel.setSizePolicy(sizePolicy)
        self.ObjectNameLabel.setBaseSize(QtCore.QSize(-30172, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.ObjectNameLabel.setFont(font)
        self.ObjectNameLabel.setToolTipDuration(-1)
        self.ObjectNameLabel.setStyleSheet("QLabel { color: white; font-size: 35px; font-family: Bahnschrift; }")
        self.ObjectNameLabel.setText("Earth")
        self.ObjectNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ObjectNameLabel.setObjectName("ObjectNameLabel")
        self.timeSlider = QtWidgets.QSlider(parent=Overlay)
        self.timeSlider.setGeometry(QtCore.QRect(120, 20, 160, 22))
        self.timeSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background: #2E2F38;  /* Dark, clean base */\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #2A2D37; \n"
"    border: 2px solid #3D4250;\n"
"    width: 16px;  \n"
"    height: 16px;\n"
"    margin: -6px 0;\n"
"    border-radius: 8px;\n"
"    transition: background 0.2s ease-in-out, transform 0.1s ease-in-out;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background:#5A5F74;  /* Subtle hover effect */\n"
"    transform: scale(1.1); /* Interactive feedback */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal, \n"
"QSlider::add-page:horizontal {\n"
"    background: #2E2F38; /* Matches groove, no highlight */\n"
"    border-radius: 3px;\n"
"}")
        self.timeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.sunButton = QtWidgets.QPushButton(parent=Overlay)
        self.sunButton.setGeometry(QtCore.QRect(70, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.sunButton.setFont(font)
        self.sunButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.sunButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.sunButton.setObjectName("sunButton")
        self.neptuneButton = QtWidgets.QPushButton(parent=Overlay)
        self.neptuneButton.setGeometry(QtCore.QRect(1728, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.neptuneButton.setFont(font)
        self.neptuneButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.neptuneButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.neptuneButton.setObjectName("neptuneButton")
        self.mercuryButton = QtWidgets.QPushButton(parent=Overlay)
        self.mercuryButton.setGeometry(QtCore.QRect(277, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.mercuryButton.setFont(font)
        self.mercuryButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.mercuryButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.mercuryButton.setObjectName("mercuryButton")
        self.venusButton = QtWidgets.QPushButton(parent=Overlay)
        self.venusButton.setGeometry(QtCore.QRect(484, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.venusButton.setFont(font)
        self.venusButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.venusButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.venusButton.setObjectName("venusButton")
        self.marsButton = QtWidgets.QPushButton(parent=Overlay)
        self.marsButton.setGeometry(QtCore.QRect(898, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.marsButton.setFont(font)
        self.marsButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.marsButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.marsButton.setObjectName("marsButton")
        self.earthButton = QtWidgets.QPushButton(parent=Overlay)
        self.earthButton.setGeometry(QtCore.QRect(691, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.earthButton.setFont(font)
        self.earthButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.earthButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.earthButton.setObjectName("earthButton")
        self.jupiterButton = QtWidgets.QPushButton(parent=Overlay)
        self.jupiterButton.setGeometry(QtCore.QRect(1105, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.jupiterButton.setFont(font)
        self.jupiterButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.jupiterButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.jupiterButton.setObjectName("jupiterButton")
        self.uranusButton = QtWidgets.QPushButton(parent=Overlay)
        self.uranusButton.setGeometry(QtCore.QRect(1520, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.uranusButton.setFont(font)
        self.uranusButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.uranusButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.uranusButton.setObjectName("uranusButton")
        self.saturnButton = QtWidgets.QPushButton(parent=Overlay)
        self.saturnButton.setGeometry(QtCore.QRect(1313, 1010, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.saturnButton.setFont(font)
        self.saturnButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.saturnButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A2D37; /* Rich dark gray, no flat black */\n"
"    color: #E3E6EE; /* Soft off-white text */\n"
"    font: bold 12pt \"Bahnschrift\";\n"
"    border: 2px solid #3D4250; /* Subtle border */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    transition: all 0.2s ease-in-out;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); /* Subtle depth effect */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343844; /* Slightly lighter on hover */\n"
"    border-color: #3D4250;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E2028; /* Darker pressed effect */\n"
"    border-color: #FFFFFF;\n"
"}\n"
"@keyframes glowPulse {\n"
"    0% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"    50% { box-shadow: 0px 0px 15px rgba(122, 129, 255, 0.7); }\n"
"    100% { box-shadow: 0px 0px 5px rgba(122, 129, 255, 0.4); }\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #FFFFFF;\n"
"    animation: glowPulse 1.5s infinite alternate;\n"
"}")
        self.saturnButton.setObjectName("saturnButton")
        self.fps_text = QtWidgets.QLabel(parent=Overlay)
        self.fps_text.setGeometry(QtCore.QRect(40, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.fps_text.setFont(font)
        self.fps_text.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.fps_text.setObjectName("fps_text")
        self.simulation_speed_text = QtWidgets.QLabel(parent=Overlay)
        self.simulation_speed_text.setGeometry(QtCore.QRect(170, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        self.simulation_speed_text.setFont(font)
        self.simulation_speed_text.setStyleSheet("QLabel { color: white; font-size: 20px; font-family: Bahnschrift; }")
        self.simulation_speed_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.simulation_speed_text.setObjectName("simulation_speed_text")
        self.checkBox = QtWidgets.QCheckBox(parent=Overlay)
        self.checkBox.setGeometry(QtCore.QRect(30, 130, 321, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=Overlay)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 160, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Overlay)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 190, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=Overlay)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 240, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(False)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:  transparent;\n"
"    border: 2px solid white;\n"
"    position: relative;\n"
"\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    border: 2px solid #ffcc99;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #ffcc99;\n"
"    border: 2px solid #ffcc99;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    spacing: 10px; /* Space between checkbox and text */\n"
"    font-size: 14px;\n"
"     color: white;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    color: #ffcc99;\n"
"}\n"
" ")
        self.checkBox_4.setObjectName("checkBox_4")

        self.retranslateUi(Overlay)
        QtCore.QMetaObject.connectSlotsByName(Overlay)

    def retranslateUi(self, Overlay):
        _translate = QtCore.QCoreApplication.translate
        Overlay.setWindowTitle(_translate("Overlay", "Form"))
        self.sunButton.setText(_translate("Overlay", "SUN"))
        self.neptuneButton.setText(_translate("Overlay", "NEPTUNE"))
        self.mercuryButton.setText(_translate("Overlay", "MERCURY"))
        self.venusButton.setText(_translate("Overlay", "VENUS"))
        self.marsButton.setText(_translate("Overlay", "MARS"))
        self.earthButton.setText(_translate("Overlay", "EARTH"))
        self.jupiterButton.setText(_translate("Overlay", "JUPITER"))
        self.uranusButton.setText(_translate("Overlay", "URANUS"))
        self.saturnButton.setText(_translate("Overlay", "SATURN"))
        self.fps_text.setText(_translate("Overlay", "FPS: 60"))
        self.simulation_speed_text.setText(_translate("Overlay", "1"))
        self.checkBox.setText(_translate("Overlay", "Normal Timestep (Best Performance)"))
        self.checkBox_2.setText(_translate("Overlay", "High Timestep (No Moons)"))
        self.checkBox_3.setText(_translate("Overlay", "Highest Timestep (No Moons)"))
        self.checkBox_4.setText(_translate("Overlay", "Performance Mode"))
